### ISSUE TITLE
Leverage the entity module to reduce the complexity of content_entity_base.

### ISSUE THREAD

**Issue by Jaesin** [Jaesin/content_entity_base#15]
List of issues:
- [x] https://github.com/Jaesin/content_entity_base/issues/16
- [x] https://github.com/Jaesin/content_entity_base/issues/17
- [x] https://github.com/Jaesin/content_entity_base/issues/18
- [ ] https://github.com/fago/entity/issues/24
- [x] https://github.com/Jaesin/content_entity_base/issues/20
- [x] https://github.com/Jaesin/content_entity_base/issues/21
- [x] https://github.com/Jaesin/content_entity_base/issues/22
- [ ] https://github.com/fago/entity/issues/25
- [x] https://github.com/Jaesin/content_entity_base/issues/23
- [x] https://github.com/Jaesin/content_entity_base/issues/24
- [x] https://github.com/Jaesin/content_entity_base/issues/25

**Comment by heddn** [comment]
+1

**Comment by dawehner** [comment]
I'll open a couple of subtasks to suggest what we can do

**Comment by heddn** [comment]
Is this stalled out? Can I use ceb at this point or should I stick with extending entity module (or core directly)?

**Comment by dawehner** [comment]
We are working hard to get stuff into entity module at the moment, but there hasn't been too much work recently, indeed, to get stuff from entity back to ceb

**Comment by Jaesin** [comment]
With the added complexity of keeping up with deprecated classes in the entity module as things get moved into core, we decided to keep our own classes in CEB for the moment. 

At some point in the future there will be a 8.x-2.x version of CEB that leverages more of the new entity related features of 8.1.x and 8.2.x in core. There will likely be some subtle api differences as things go through the process of being adopted into core.
