### ISSUE TITLE
\Drupal\content_entity_base\Entity\Form\EntityRevisionRevertForm can be replaced by https://github.com/fago/entity/pull/17

### ISSUE THREAD

**Issue by dawehner** [Jaesin/content_entity_base#20]
Once https://github.com/fago/entity/pull/17 is done, \Drupal\content_entity_base\Entity\Form\EntityRevisionDeleteForm would not be needed anymore

**Comment by dawehner** [comment]
In order to do that, we need to get rid of `\Drupal\content_entity_base\Entity\EntityRevisionLogInterface` and `\Drupal\content_entity_base\Entity\TimestampedRevisionInterface` first

**Comment by Jaesin** [comment]
We decided to go another way on this one =)
