### ISSUE TITLE
Replace the custom entity revision interfaces

### ISSUE THREAD

**Issue by dawehner** [Jaesin/content_entity_base#24]
CEB currently provides a couple of interfaces to expose some revision information for entities:

`\Drupal\content_entity_base\Entity\EntityRevisionLogInterface` and `\Drupal\content_entity_base\Entity\TimestampedRevisionInterface` and `\Drupal\content_entity_base\Entity\ExpandedEntityRevisionInterface`

All those could be replaced by using `\Drupal\entity\Revision\EntityRevisionLogInterface` and then also using `\Drupal\entity\Revision\EntityRevisionLogTrait` on the actual entity base class

**Comment by Jaesin** [comment]
We decided to keep the CEB classes
