### ISSUE TITLE
Entity paths default to /admin/{entity_content}/#

### ISSUE THREAD

**Issue by heddn** [Jaesin/content_entity_base#41]
Putting these entities under the admin path seems wrong. Is that the intention?

**Comment by heddn** [comment]
For example, /admin/ceb_test_entity_content/1. This changes it to /ceb_test_entity_content/1.  If we go that route, we should change more than just the 'view' path. All the paths should change. But then the edit, delete paths are no longer admin paths.

**Comment by heddn** [comment]
This is coming from DefaultHtmlRouteProvider provided by entity module. We'd either need to fix it there, or in EntityRouteProviderSubscriber or extend in CEB or ignore this as problem.

Me thinks all paths except for the canonical path should be admin routes.

**Comment by dawehner** [comment]
Afaik this paths have been chosen, as the entities we created all had admin paths. I don't care much about it, to be honest :)

**Comment by heddn** [comment]
I'd think most people wouldn't want them as admin paths. But if we can get #43 committed, then switching around the paths will be a fairly easy step when cloning the test project. So I guess I don't care so much if this gets merged. I do care about #43 though.

**Comment by Jaesin** [comment]
See #42
