### ISSUE TITLE
Revisions don't seem to be functional

### ISSUE THREAD

**Issue by heddn** [Jaesin/content_entity_base#44]
See https://github.com/edysm/nuevas-esperanzas/tree/master/modules/custom/nica_entity as an example. I've copied ceb test, renamed stuff and most works. But revisions don't seem to be functional at the moment. Will that get fixed or am I doing something wrong? I've changed very little except for renames, so me thinks something is not working. The error I get is access denied.

Inside EntityRevisionRouteAccessChecker->access(), the loaded entity revision is null.

**Comment by dawehner** [comment]
We are using that module on production with revision support, but honestly the ceb_test entity was never really tested. Can you use that module without the entire project, so someone can quickly debug it?

**Comment by heddn** [comment]
Yes, it can be used separate from the rest of the site. There's nothing in it but the entity definition.

**Comment by Jaesin** [comment]
I am thinking that if we can get Drupal console integration sorted, we can create a test entity on the fly. Then we can remove `ceb_test`.

I must admit when I test manually, it's with a `console generate:entity:ceb` entity these days.

**Comment by Jaesin** [comment]
See #56
