### ISSUE TITLE
Get rid of the FooEntityPermissions proxy class and the foo.permisisons.yml file for custom entity modules.

### ISSUE THREAD

**Issue by Jaesin** [Jaesin/content_entity_base#49]
FooEntityPermissions is used to proxy the permissions callback to Drupal\content_entity_base\Entity\Access\EntityBasePermissions.

We should be able to specify the permission handler in the entity definition.

**Comment by Jaesin** [comment]
Best case scenario, we can get rid of the `foo.permisisons.yml` file as well as it's pretty safe to assume all custom entities will need permissions of some kind.

**Comment by dawehner** [comment]
So now that core has the functionality, can we do it now?

**Comment by Jaesin** [comment]
Ref: https://www.drupal.org/node/2673726

Committed to 8.1 but not 8.0.x. This one still needs tests but we have to clean up the existing tests first.

**Comment by Jaesin** [comment]
Tests were added with #50 .
