### ISSUE TITLE
Access denied for `user/1` when accessing `admin/content/foo/1/revisions`

### ISSUE THREAD

**Issue by Jaesin** [Jaesin/content_entity_base#56]
The revision history page gets an access denied message. 

Needs test.

**Comment by heddn** [comment]
Seems similar to what I see in #44

**Comment by Jaesin** [comment]
Yep. We gotta add a test for it and fix it. I'd rather rely on the entity module for this but entity has issues with the revision list as well. See fago/entity#36

**Comment by Jaesin** [comment]
I manually tested this in the latest revision and there is an automated test for it as well.
