### ISSUE TITLE
composer.json mispelling

### ISSUE THREAD

**Issue by charlotte17** [Jaesin/content_entity_base#61]
```
     "require": {
-        "drupal/enity": "8.1.x-dev"
+        "drupal/entity": "~8"
     }
```

**Comment by dawehner** [comment]
Note: https://github.com/Jaesin/content_entity_base/pull/48 includes that as well

**Comment by Jaesin** [comment]
Thanks @charlotte17 Indeed the entry is incorrect but as in @dawehner's pull request we need to keep this module synced to the 8.x-0.x verison of the entity module because there will be changes in 8.x-1.x because of changes in drupal core.
