### ISSUE TITLE
Add migrate support to simple entity

### ISSUE THREAD

**Issue by heddn** [Jaesin/content_entity_base#9]
If we go to the work of adding a simple entity, then being able to migrate data into it should also be simple. Otherwise, what is the point...

This is a reminder to ourself to build that functionality.

**Comment by dawehner** [comment]
Do we need anything? I mean I used migrate to migrate into content_entity_base content and I didn't had to do any custom stuff on the migrate side

**Comment by heddn** [comment]
I might not need it.

**Comment by dawehner** [comment]
@heddn What did you had in mind about it?
